package com.github.henriquesmoco.decathlon;

public enum Evento {
	CORRIDA_100_METROS,
	CORRIDA_400_METROS,
	CORRIDA_1500_METROS,
	CORRIDA_110_METROS_COM_BARREIRAS,		
	ARREMESSO,
	LANCAMENTO_DISCO,
	LANCAMENTO_DARDO,		
	SALTO_A_DISTANCIA,
	SALTO_EM_ALTURA,
	SALTO_COM_VARA
}